spring.application.name=dipl

# H2-Datenbank als Datei (persistente DB)
spring.datasource.url=jdbc:h2:file:./data/dipl-db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2-Konsole (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

stripe.secret.key=sk_test_51TAVKC4mf4P8i383nX40xaSrGnH1XzAITxiJw8j0bGkM5A99qWqA03AGXpVKYLSmvZH2DyodS13rnGxLWRlS9vqR003d4roifm
stripe.webhook.secret=whsec_c490a07b5015776741be4b1fa2d7ba6c6e85df90c92400532c2d828b6368be00
app.frontend.url=http://localhost:4200

